version: "3.0"
services:  
  incident:
    image: "commandcenter/icc/deliveryserver:${TAG:-latest}"
    container_name: "commandcenter.icc.deliveryserver"
    network_mode: "host"
    user: root
    volumes:
      - "/usr/CommandCenter/log/icc/deliveryserver:/usr/CommandCenter/icc/Tools/Logs/CommandCenter.ICC.DeliveryServer"
      - "/etc/localtime:/etc/localtime"      
    logging:
      driver: "json-file"
      options:
        max-size: "80M"
        max-file: "10"
    restart: "always"
    environment:
      - UCMS_ADDR=192.168.0.168:28025